### ISSUE TITLE
disappearing background, icons, checks, etc. when loaded with thousands of records

### ISSUE THREAD

**Issue by Lyradb** [Openworx/backend_theme#17] opened 2017-07-27 23:11 UTC
I like the theme and decided to try it, I loaded with thousands of records on products, chart of accounts, partners and the main UI is having trouble rendering the background and in some part it does not display the icons.

And even the checkbox in settings/configuration, the check is not showing at all.

When I remove the backend_theme, the rest of the apps works perfectly.

Have anyone same issues with me?

![image](https://user-images.githubusercontent.com/579973/28695858-59be6828-7364-11e7-9fd6-a36e53e61925.png)

**Comment by TheRealHatCoder** [comment] 2017-08-02 19:55
Duplicate of Issue #16

**Closed as completed** 2017-10-01 21:33 UTC
